spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: authModule
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
        - id: chatModule1
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/**
        - id: chatModule2
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/ws/info/**
        - id: chatModule3
          uri: lb:ws://chat-server
          predicates:
            - Path=/chat-server/ws/**
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true