spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: authModule
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
        - id: chatModule
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/api/**
        - id: chatModule
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/ws/info/**
        - id: chatModule
          uri: lb:ws://chat-server
          predicates:
            - Path=/chat-server/ws/**
management:
  endpoints:
    web:
      exposure:
        include: refresh
