spring:
  cloud:
    stream:
      bindings:
        user:
          binder: kafka
          destination: user
          group: user-group
          contentType: 'application/json'
          consumer:
            concurrency: 1